site_name: Baulehrer-Kaufmann
site_description: Wissen · Technik · Bratwurst
site_author: Stephan Kaufmann
site_url: https://kaufi-cloud.de
docs_dir: docs

theme:
  name: material
  custom_dir: docs/overrides
  language: de
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Dunkelmodus
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Hellmodus
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/custom.css

nav:
  - Start: index.md
  - Bautechnik:
    - Links: 02 Bautechnik/B01 - Links (Bautechnik).md
  - Musik:
    - Heavy Metal: 01 Musik/M01 - Heavy Metal.md
    - Epic Doom: 01 Musik/M02 - (Epic) Doom.md
    - Sonstiges: 01 Musik/M03 - Was sonst noch fetzt.md

plugins:
  - search:
      lang: de

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
